Donation Form Skeleton Complete With Some Validation
ctc-uci/patriots-and-paws-frontend pull request #15
Opened 2022-11-12 23:27 UTC by ThatMegamind

Authors: Michael Pien, Kevin Liu

**What does this PR contain?**

All donation form fields completed and some validation implemented.

**How did you test these changes?**

Clicking the submit button with empty fields or incorrect fields results in the proper error messages.

Attach images (if applicable)

![Screen Shot 2022-11-12 at 3 26 18 PM](https://user-images.githubusercontent.com/92563733/201498545-e069436c-ecb5-477c-b6fd-3b76be9758b2.png)

Closes https://github.com/ctc-uci/patriots-and-paws-frontend/issues/9

2022-11-12 23:29 UTC, ctc-devops commented on src/App.jsx
> +import DonationForm from './components/DonationForm';
🚫 **[eslint]** <[import/no-named-as-default](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-named-as-default.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Parse errors in imported module './components/DonationForm': Unexpected token . (39:44)

2022-11-12 23:29 UTC, ctc-devops commented on src/App.jsx
> +import DonationForm from './components/DonationForm';
🚫 **[eslint]** <[import/no-named-as-default-member](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-named-as-default-member.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Parse errors in imported module './components/DonationForm': Unexpected token . (39:44)

2022-11-12 23:29 UTC, ctc-devops commented on src/components/DonationForm.jsx
> +            <FormControl isInvalid={errors?.firstName} width="47%">
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Parsing error: Unexpected token .

2022-11-15 08:15 UTC, ctc-devops commented on src/components/DonationForm.jsx
> +      <form onSubmit={handleSubmit(data => console.log(data))}>
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-11-15 08:29 UTC, jrock-3 requested changes
Codewise, just one change to make, otherwise it looks ready to merge in and start the next iteration of the form!

2022-11-15 08:29 UTC, jrock-3 commented on src/components/DonationForm.jsx
> +import './DonationForm.css';
Use module.css, see the [PNP Best Programming Practices](https://drive.google.com/file/d/1EfQjal0X2wpreBFlGLLqZznisbncYdFf/view) for more info

2022-11-15 08:29 UTC, jrock-3 commented on src/components/DonationForm.jsx
> +            <FormControl isInvalid={errors && errors.firstName} width="47%">
(not a comment to change anything) This line and a bunch of other `FormControl`/`FormErrorMessage` lines were using optional chaining (ie `error.?firstName`) in order to ensure attributes existed, but it's typically better practice to implement it as I did here, with `errors && errors.firstName`. Just something to make a note of for the future

2022-11-15 08:41 UTC, jrock-3 requested changes
forgot to add one change

2022-11-15 08:41 UTC, jrock-3 commented on src/components/DonationForm.jsx
> +import React from 'react';
`DonationForm.jsx` and `DonationForm.module.css` should be in their own folder named `DonationForm` within `/components`, see [PNP Best Programming Practices](https://drive.google.com/file/d/1EfQjal0X2wpreBFlGLLqZznisbncYdFf/view) for more info

2022-11-17 07:03 UTC, jrock-3 approved these changes
yuh

2022-11-17 07:10 UTC, merged