Implement Auth
ctc-uci/patriots-and-paws-frontend pull request #18
Opened 2022-11-19 17:28 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #10

2022-11-28 04:19 UTC, hang-m-cao requested changes
Great job getting authentication up and running; this is amazing!

I left comments about setting up the forms and best practices to make the code a little cleaner. There are also notes about things that may change in the future once we finalize some decisions; feel free to add any input on them! I did not look too much at the styling since that is subject to change once the design is finished.

Also, thanks for the patience waiting for me review this :)

2022-11-28 04:19 UTC, hang-m-cao commented on .github/workflows/scripts/reviewReviewed.js
> +              text: `${reviewer} has :discodog:APPROVED your PR <${url}|${title}>`,
Let's revert this change. Even though it might not affect anything (and is probably from before the ignore file), let's not change anything in the `.github` folder.

2022-11-28 04:19 UTC, hang-m-cao commented on src/App.jsx
> +          <Route exact path="/email-action" element={<EmailAction redirectPath="/" />} />
The `redirectPath` here should lead the user to `/login` instead. A null code when trying to access the `/email-action` route means the URL is invalid (even though theoretically it should be fine with auth correctly set up).

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Register/Register.jsx
> +              <Radio value={SUPERADMIN_ROLE}>Superadmin</Radio>
Superadmin should not be an option as of now. We are looking to have only one superadmin account.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Register/Register.jsx
> +  const [role, setRole] = useState(ADMIN_ROLE);
To make validation easier, let's use the `yup` library. Refer to [this example form FYA](https://github.com/ctc-uci/find-your-anchor-frontend/blob/dev/src/components/Register/RegisterForm.jsx) which essentially creates a schema for all of the necessary variables with the corresponding checks. There should also be a string regex check if you look up the documentation.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Register/Register.jsx
> +            }}
Once you have the `<form>` set up, you can give this button the attribute `type="submit"`, and it should automatically call the `handleSubmit` function. Makes it a bit cleaner :)

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Register/Register.jsx
> +        /^(?=.*[a-z])(?=.*[A-Z])(?=.*[@$!%*?&])[A-Za-z@$!%*?&]{8,}$/;
Can we add digits to the check? Require at least one and have digits count as a part of the character count.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Register/Register.jsx
> +        <FormControl isRequired className={styles['register-form']}>
Let's also give the user the option to submit the form on enter (a minor thing but it's often an expected functionality and it doesn't hurt to have it). To do so, wrap the form in a `form` tag (you may have to edit the styling), and pass an `onSubmit` function.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/ResetPassword/ResetPassword.jsx
> +        /^(?=.*[a-z])(?=.*[A-Z])(?=.*[@$!%*?&])[A-Za-z@$!%*?&]{8,}$/;
Since this regex is used more than once, let's move it to the `utils.js` file and update it to match the comment on the Register component.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/ResetPassword/ResetPassword.jsx
> +const ResetPassword = ({ code }) => {
Same comments here as the Register Form: add `yup` validation and the form submission flow.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Login/Login.jsx
> +          <FormControl className={styles['login-form']} isRequired>
Same comments here as the Register Form below: add `yup` validation and the form submission flow.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Logout/Logout.jsx
> +      clearCookies(cookies);
Cookies should be cleared after successful logout. This is already taken care of in the `logout` method.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Logout/Logout.jsx
> +import React, { useState } from 'react';
Just a note: this is fine for now, but the structure might change later as it's typically a logout button and uou usually don't navigate to a page just to log out.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Logout/Logout.jsx
> +          }}
Reduce this to `onSubmit={handleSubmit}`.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/ForgotPassword/ForgotPassword.jsx
> +const ForgotPassword = () => {
Same comments here as the Register Form below: add `yup` validation and the form submission flow.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Dashboard/Dashboard.jsx
> +      <p>Hello, {user.first_name}!</p>
Just a note: once the changes in the backend have been made, this should be camelCase.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Login/Login.jsx
> +    checkUserAuthentication();
Just out of curiosity, I wonder if we could add this to `AuthUtils` to reuse since `ProtectedRoutes` also uses the same function.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Login/Login.jsx
> +          </Alert>
I like this idea. Let's run this by the designers to see what they think about it and to make them aware if they need to add it to their wireframes.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Register/Register.jsx
> +        <Heading className={styles['register-title']}>Register</Heading>
Nit-pick: since this will be used by admins to create an account instead of users registering themselves, let's change it to something like `Create Account` and you can do the same for the file name.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Register/Register.jsx
> +              <Radio value={DRIVER_ROLE}>Driver</Radio>
To get closer to how we will be using it, can you put this component behind a protected route and conditionally render the options based on role? (superadmins have both options, admins just have drivers)

2022-11-28 04:19 UTC, hang-m-cao commented on src/App.jsx
> +          <Route exact path="/email-action" element={<EmailAction redirectPath="/" />} />
We might also be changing this route to a more suitable name, but we will let you know (unless you guys also have suggestions. "email-action" is not quite fitting for what this route is for/doing).

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/ResetPassword/ResetPassword.jsx
> +        )}
We can simplify this into one check with the ternary operator. See the best practice **conditional rendering**.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Logout/Logout.jsx
> +import React, { useState } from 'react';
If you want, see if you could import this inside the Dashboard as a button.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Dashboard/Dashboard.jsx
> +import React, { useEffect, useState } from 'react';
This should be a page, not a component.

2022-11-28 04:19 UTC, hang-m-cao commented on src/components/Login/Login.jsx
> +      setErrorMessage(err.message);
Saying something about "FireBase error auth" doesn't make sense to the user, so see if you could parse the error returned to be more user-friendly.

2022-11-28 04:25 UTC, hang-m-cao commented on src/components/Register/Register.jsx
> +  const [phoneNumber, setPhoneNumber] = useState('');
Can we add validation to the phone numbers to be valid? For now, the check can be for a length of 10 digits.

2022-11-28 21:29 UTC, carolibn commented on src/components/Login/Login.jsx
> +    checkUserAuthentication();
We can move `userIsAuthenticated` to `AuthUtils`, but we can't move `checkUserAuthentication` because the set functions are from `useState`

2022-12-13 09:33 UTC, ctc-devops commented on src/App.jsx
> +import EditDonationForm from './pages/Dashboard/EditDonationForm';
🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module './pages/Dashboard/EditDonationForm'.

2022-12-13 09:33 UTC, ctc-devops commented on src/App.jsx
> +import EditDonationForm from './pages/Dashboard/EditDonationForm';
🚫 **[eslint]** <[import/extensions](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/extensions.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing file extension for "./pages/Dashboard/EditDonationForm"

2022-12-13 09:33 UTC, ctc-devops commented on src/App.jsx
> +import Drivers from './pages/Dashboard/Drivers';
🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module './pages/Dashboard/Drivers'.

2022-12-13 09:33 UTC, ctc-devops commented on src/App.jsx
> +import Drivers from './pages/Dashboard/Drivers';
🚫 **[eslint]** <[import/extensions](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/extensions.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing file extension for "./pages/Dashboard/Drivers"

2022-12-13 09:33 UTC, ctc-devops commented on src/App.jsx
> +import DriverRoutes from './pages/Dashboard/DriverRoutes';
🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module './pages/Dashboard/DriverRoutes'.

2022-12-13 09:33 UTC, ctc-devops commented on src/App.jsx
> +import DriverRoutes from './pages/Dashboard/DriverRoutes';
🚫 **[eslint]** <[import/extensions](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/extensions.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing file extension for "./pages/Dashboard/DriverRoutes"

2022-12-13 09:34 UTC, hang-m-cao approved these changes, later dismissed
this looks great! it was definitely a lot but you guys did amazing :)

2022-12-13 09:39 UTC, merged