25-manage-staff-page
ctc-uci/patriots-and-paws-frontend pull request #31
Opened 2023-01-12 00:18 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #25

2023-01-19 06:07 UTC, ctc-devops commented on src/components/DisplayedProfile/DisplayedProfile.jsx
> +import profilePicture from '../../assets/profilePicture.png';
🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.27.5/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module '../../assets/profilePicture.png'.

2023-01-25 18:08 UTC, hang-m-cao requested changes
It's looking good! I made some comments about things to fix or remove because of some changes to the flow and design. A couple of comments point out features that are being pushed to next sprint's task, so make note of those. 

Other than that, good job (especially being technically a 1-week sprint for you)! 🥳

2023-01-25 18:08 UTC, hang-m-cao commented on src/pages/ManageStaff/ManageStaff.jsx
> +      const driverData = data.filter(d => d.role === 'driver');
Let's use the `DRIVER_ROLE` variable from `AUTH_ROLES.AUTH_ROLE` to check the role value.

2023-01-25 18:08 UTC, hang-m-cao commented on src/pages/ManageStaff/ManageStaff.jsx
> +    const adminData = usersCopy.filter(user => user.role === 'admin' || user.role === 'superadmin');
Can we also filter this to not include the currently logged-in user's account? We can check against the `id` of the user from cookies.

2023-01-25 18:08 UTC, hang-m-cao commented on src/pages/ManageStaff/ManageStaff.jsx
> +  const [userType, setUserType] = useState('Driver');
To keep it consistent (and easier for us), we're going to have everything be kept as **Staff** so there's no need to distinguish based on the role for display "Staff" vs. "Driver".

2023-01-25 18:08 UTC, hang-m-cao commented on src/pages/ManageStaff/ManageStaff.jsx
> +              placeholder={isSuperAdmin ? 'Search Staff' : 'Search Drivers'}
Change to just **Search Staff**.

2023-01-25 18:08 UTC, hang-m-cao commented on src/components/CreateAccount/CreateAccount.jsx
> +      refreshData();
Ideally, we would not want to refresh the page to retrieve all the data again, but instead, we would make the backend call and then manually update that piece of information. We can push this to the next task.

2023-01-25 18:08 UTC, hang-m-cao commented on src/components/CreateAccount/CreateAccount.jsx
>        // await registerWithEmailAndPassword(user, navigate, '/login?signup=success');
With the new flow, we probably do not need this addition anymore because we will not be redirecting the page. So, we can delete this.

2023-01-25 18:08 UTC, hang-m-cao commented on src/components/UserTable/UserTable.jsx
> +
Can you move this to `utils.jsx`? There's a high chance it can get reused.

2023-01-25 18:08 UTC, hang-m-cao commented on src/components/UserTable/UserTable.jsx
> +              </Td>
Instead of creating separate modals for each user, there should be only one of each modal that would accept information about the user to populate itself. So, in a way, the modals should belong to the page and not the table row (ie. bring the modals outside of the table).

2023-01-25 18:08 UTC, hang-m-cao commented on src/components/CreateAccount/CreateAccount.jsx
>      firstName: yup.string().required('Please enter your first name'),
Nit-pick: all of these error messages should be changed to reflect creating the account for another user (ie. not 'your').

2023-01-25 18:08 UTC, hang-m-cao commented on src/components/EditAccountModal/EditAccountModal.jsx
> +                          )}
Quick change to the Figma: we won't be displaying roles in the edit modal since it can't be changed anyway.

2023-01-25 18:08 UTC, hang-m-cao commented on src/components/EditAccountModal/EditAccountModal.jsx
> +  };
Confirming that this functionality is pushed to the next sprint's task. Can you add a TODO comment just as a reminder?

2023-01-25 18:08 UTC, hang-m-cao commented on src/components/EditAccountModal/EditAccountModal.jsx
> +const EditAccountModal = ({ isSuperAdmin, memberType, userProfile }) => {
Nit-pick: the name `userProfile` kind of implies it's the logged-in user's profile. To make it more clear, `staffProfile`, `accountInfo`, or any other alternatives might be better options.

2023-01-25 18:08 UTC, hang-m-cao commented on src/components/EditAccountModal/EditAccountModal.jsx
> +    firstName: yup.string().required('Please enter your first name'),
Change error messages (see comment on `CreateAccount.jsx`).

2023-01-25 18:08 UTC, hang-m-cao commented on src/components/CreateAccount/CreateAccount.jsx
> +const CreateAccount = ({ isSuperAdmin, memberType, refreshData }) => {
We won't be needing `memberType` anymore as we're keeping everything "Staff" to make it easier (I might have repeated this somewhere else in the review).

2023-01-29 22:51 UTC, hang-m-cao approved these changes
👍🏻 looks good! thanks for making the changes :)

2023-01-29 23:00 UTC, merged