Donation Form Email Confirmation and Improved Validation
ctc-uci/patriots-and-paws-frontend pull request #32
Opened 2023-01-12 23:04 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #28

2023-01-13 01:08 UTC, ctc-devops commented on src/components/DonationForm/DonationForm.jsx
> +    console.log(event.target.email1.value);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-01-13 01:08 UTC, ctc-devops commented on src/components/DonationForm/DonationForm.jsx
> +    console.log(event.target.zipcode.value);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-01-22 10:15 UTC, jrock-3 requested changes
a few major changes to make, lmk if any of my comments need further clarification

2023-01-22 10:15 UTC, jrock-3 commented on src/components/DonationForm/DonationForm.jsx
> +    ),
there's a better way to code this, check [this](https://github.com/ctc-uci/patriots-and-paws-frontend/blob/dev/src/components/ResetPassword/ResetPassword.jsx#L36) out

2023-01-22 10:15 UTC, jrock-3 commented on src/components/DonationForm/DonationForm.jsx
> +      <form onSubmit={handleSubmit(data => sendEmail(data.email1, dconfirmemailtemplate))}>
can you extract this function into an `onSubmit` so we can add more functionality in the future

2023-01-22 10:15 UTC, jrock-3 commented on src/components/DonationForm/DonationForm.jsx
> +    ),
add validation to check if default selections for `FurnitureField` are selected (as of now the default selections have a value of `''`). take a look at [this](https://stackoverflow.com/questions/66266929/how-to-use-yup-validation-on-dynamic-form-using-react-hook-form-with-usefieldarr) for inspiration

2023-02-26 21:56 UTC, closed without merging