Create Admin & Driver Nav Bar
ctc-uci/patriots-and-paws-frontend pull request #34
Opened 2023-01-13 21:59 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #24

2023-01-23 20:35 UTC, jrock-3 requested changes
functionality wise it looks good, just a few comments on code organization and styling and it should be good to go!

2023-01-23 20:35 UTC, jrock-3 commented on src/components/Navbar/DriverNavbar.jsx
> +              <Link as={NavLink} to="/user:userid">
link this to `/user/:userId` where userId is the currently logged in user (grab this from the cookies)

2023-01-23 20:35 UTC, jrock-3 commented on src/pages/dashboard/Dashboard.jsx
> +  const [isDriver, setIsDriver] = useState(false);
it's a bit verbose to add 3 state variables, you can do this in one by saving the role itself, then comparing it later on when conditionally rendering

2023-01-23 20:35 UTC, jrock-3 commented on src/pages/dashboard/Dashboard.jsx
> +        {(isSuperAdmin || isAdmin) && <AdminNavbar />}
you don't need two separate navbar components, merge it into one component that will internally conditionally render certain links based off the role

2023-01-23 20:35 UTC, jrock-3 commented on src/pages/dashboard/Dashboard.jsx
> +        {(isSuperAdmin || isAdmin) && <AdminNavbar />}
also move the navbar component to `App.jsx` and conditionally render it based off the route, whether or not the page is a login/donation form page

2023-01-23 20:35 UTC, jrock-3 commented on src/pages/dashboard/Dashboard.jsx
> +        {(isSuperAdmin || isAdmin) && <AdminNavbar />}
since the plan is to move the navbar to `App.jsx`, move the cookie fetching to the navbar component instead

2023-01-23 20:35 UTC, jrock-3 commented on src/components/Navbar/AdminNavbar.jsx
> +              <Link as={NavLink} to="/user:userid">
same comment as the one in `DriverNavbar.jsx`

2023-01-23 20:35 UTC, jrock-3 commented on src/components/Navbar/AdminNavbar.jsx
> +        </Link>
swap the order of routes and inventory

2023-01-23 20:35 UTC, jrock-3 commented on src/components/Navbar/DriverNavbar.jsx
> +          Dashboard
change this name to `Routes`

2023-01-23 20:35 UTC, jrock-3 commented on src/components/Navbar/AdminNavbar.jsx
> +import React, { useEffect, useState } from 'react';
navbars should be sticky to the top of the page, and span the entire width of the page. reference the figma as an example

2023-02-07 22:53 UTC, ctc-devops commented on src/App.jsx
> +      <Outlet />
🚫 **[eslint]** <[react/jsx-no-undef](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/jsx-no-undef.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Outlet' is not defined.

2023-02-08 05:32 UTC, jrock-3 approved these changes
lgtm

2023-02-08 05:33 UTC, merged