Manage Staff UserDetails Integration
ctc-uci/patriots-and-paws-frontend pull request #44
Opened 2023-01-29 23:06 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #42

2023-02-03 05:26 UTC, ctc-devops commented on src/pages/ManageStaff/ManageStaff.jsx
> +    console.log(data);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-02-03 05:26 UTC, ctc-devops commented on src/pages/ManageStaff/ManageStaff.jsx
> +    console.log(users);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-02-18 02:29 UTC, jrock-3 requested changes
Great work guys! This is a huge task, and other than a few bugs and comments we've left, it's really solid!

A few general details:
- Bug: On create new user, it logs the current user out
- Bug: `EditAccountModal` password fields aren't being cleared after clicking "x" or cancel
  - When exiting without saving, pop up an [alert dialogue](https://chakra-ui.com/docs/components/alert-dialog) instead of the modal currently being used
  - Clicking "x" doesn't prompt confirmation modal (only clicking cancel does)
- `UserDetail` component wasn't integrated into `ManageStaff`, instead `EditAccountModal` was made to match `UserDetails` (whether or not we want to merge the two components together to make it reusable is still pending)

2023-02-18 02:29 UTC, jrock-3 commented on src/components/CreateAccount/CreateAccount.jsx
> +                                    <li>1 symbol</li>
Use Chakra `UnorderedList` & `ListItem` instead of `ul` & `li`, respectively. Also React doesn't like when you nest a `ul` tag inside a `p` tag, which is what we're doing here (recall: `Text` components are essentially `p` tags). Since we'll be using all Chakra components, you can just add the styling (`fontSize` & `fontWeight`) to the `UnorderedList`

2023-02-18 02:29 UTC, jrock-3 commented on src/components/CreateAccount/CreateAccount.jsx
> +                            <option value="admin" selected>
Adding the `selected` prop to `option` tags is outdated, move that functionality to the `Select` component by adding a `defaultValue` prop set to _admin_.

2023-02-18 02:29 UTC, jrock-3 commented on src/components/DeleteAccountModal/DeleteAccountModal.jsx
>  import React from 'react';
Convert this modal to an [`Alert Dialogue`](https://chakra-ui.com/docs/components/alert-dialog)

2023-02-18 02:29 UTC, jrock-3 commented on src/pages/ManageStaff/ManageStaff.jsx
> +      setDisplayedUsers(driverData);
If the user is an admin, make sure to call `setAllUsers(driverData)`, otherwise admins never see anything (since they can't filter)

2023-02-18 02:29 UTC, jrock-3 commented on src/components/UserTable/UserTable.jsx
>                {isSuperAdmin ? (
Use `&&` instead of ternary operator so we can properly conditionally render the column label.

2023-02-18 02:29 UTC, jrock-3 commented on src/components/UserTable/UserTable.jsx
> +                {isSuperAdmin ? (
Use `&&` instead of ternary operator so we can properly conditionally render the column label.

2023-02-18 02:29 UTC, jrock-3 commented on src/components/DeleteAccountModal/DeleteAccountModal.jsx
> +  staffProfile: PropTypes.arrayOf(
Get rid of the outer `PropTypes.arrayOf` section because you aren't passing in an array of user data.

2023-02-18 02:29 UTC, jrock-3 commented on src/components/UserTable/UserTable.jsx
> +  const [deleteUserData, setDeleteUserData] = useState([]);
The default value for these should be empty objects (`{ }`) instead of empty lists, since the values they end up being set to are objects.

2023-02-18 02:29 UTC, jrock-3 commented on src/components/UserTable/UserTable.jsx
> +              <Tr key={`${user.id}`}>
Use `user.email` instead of `user.id` since we get PropType errors when adding a new user locally (since they haven't been assigned an `id` yet)

2023-02-20 08:10 UTC, jrock-3 requested changes
Two small changes, and you guys are all done! Great job!

2023-02-20 08:10 UTC, jrock-3 commented on src/App.jsx
> +                roles={[SUPERADMIN_ROLE, ADMIN_ROLE, DRIVER_ROLE]}
Drivers can't access manage staff, only admins and superadmins

2023-02-20 08:10 UTC, jrock-3 commented on src/utils/AuthUtils.js
> +  // sendEmailVerification,
delete if no longer using

2023-02-21 19:26 UTC, jrock-3 submitted a review, later dismissed
lgtm!

2023-02-21 19:31 UTC, ctc-devops commented on src/pages/ManageStaff/ManageStaff.jsx
> +    const userId = getCurrentUserId();
🚫 **[eslint]** <[no-undef](https://eslint.org/docs/rules/no-undef)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'getCurrentUserId' is not defined.

2023-02-21 19:33 UTC, merged