Inventory Match Design
ctc-uci/patriots-and-paws-frontend pull request #50
Opened 2023-02-13 05:10 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #37

2023-02-14 18:09 UTC, hang-m-cao requested changes
I've added comments on places where we can work to make the code more concise. There also seems to be a bug with rendering the status tag of each donation in the modal. Other than that, good work so far!

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +// import React, { useState, useEffect } from 'react';
This is a duplicate of the line below, so you can remove this.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
>    } = useForm({ defaultValues: data, resolver: yupResolver(schema) });
Since we are not longer allowing editing, we don't need the yup schema or react hook form. We can directly display all the donation information.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
>    };
If `close` only calls `onClose`, we can replace all calls to `close` with `onClose`.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +  const googleMap = `https://www.google.com/maps/search/?api=1&query=${addressStreet}, ${addressUnit}, ${addressCity}, CA, ${addressZip}`;
Add a check to see if `addressUnit` is null. If it is, don't include it in the API URL query.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +              {currentStatus === 'pending' ? (
Create a config object for all of the statuses, so that it's easier to refer to them and more consistent (don't have to worry about misspellings). Refer to the `AUTH_ROLES` object [here](https://github.com/ctc-uci/patriots-and-paws-frontend/blob/dev/src/utils/AuthConfig.js). Feel free to add the object here and rename the file to `config.js`. All of the statuses are defined as noted [here](https://github.com/ctc-uci/patriots-and-paws-backend/blob/dev/server/schema/donations.sql#L4).

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +              {currentStatus === 'changes requested' && (
`currentStatus` for every donation log as `pending` instead of the actual status. This may be because the `useState` function is async and has not been updated

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +              )}
Instead of a button, render a [Chakra tag](https://chakra-ui.com/docs/components/tag). We can also simplify this code by creating an object mapping each status to its respective tag color and then accessing those values.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +                      <Input placeholder="name" {...register('firstName')} isRequired isDisabled />
Because we will be removing the react hook form, you can pass in the actual values retrieved from the backend. Do this for all of the input fields.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
>                        {errors.firstName && errors.firstName.message}
Remove all `FormErrorMessage` since there won't be any to show.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +            )}
If there's nothing to render if the condition is false, we don't need the latter half of the ternary operator (ie. the `: ( '' )`).

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +              {/* <a href="https://www.google.com/maps">Navigate to Address</a> */}
Remove this.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +    sendEmail(email, emailTemplate);
Update this function to take in a subject title, and also pass in modal header text as the subject for each email.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +          )}
Create an object mapping the status to the modal header and use that to render the component instead of conditionally checking.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +            {status === 'pending' || status === 'changes requested' ? (
The modal footer buttons currently do not change when the status has been changed. To recreate: Open a pending donation. Send a **Request Changes** email. When the email modal closes, the **Request Changes** button should be disabled.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +              </Box>
This can also be simplified by making an object mapping the status to the template body text.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +    <>
Nit-pick: because there is only one main component (ie. the `Modal`), you don' need the empty `<> </>`.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +              }}
It should also send the email.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/InventoryPage.jsx
>        );
This can also be a mapping of status to the tag color, and the text you can convert the status to capital case. Also, convert the button to a tag.

2023-02-14 18:09 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +                      <Input placeholder="name" {...register('firstName')} isRequired isDisabled />
Let's also find a way to render these as text fields instead of disabled input fields because that styling makes it hard to see the information.

2023-02-21 21:24 UTC, hang-m-cao requested changes
It's getting very close! I left additional comments addressing some bugs and cleaning up the code. Let me know if you have any questions or need more clarification about any of them.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/DonationImagesContainer.jsx
> +            alt="test"
The `alt` value should be the image description.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +  // Image,
Remove.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
We have a utils function that will construct this URL for us and also set the initial location, so let's use that! Refer to the code [here](https://github.com/ctc-uci/patriots-and-paws-frontend/blob/dev/src/utils/utils.js#L47-L61), and the change would just be to pass in the full address object in a list.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +            </Box> */}
Remove.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +              </Box>
To make the code cleaner, let's extract this to a helper function and create a mapping from the status to the `colorScheme` of the button. This component should also be a tag. The function body would return the component like so
```
return <Tag size="xs" m={5} ml={15} colorScheme=statusColor[status]> format(status) </Tag>
```
Since we have the statuses, we want to reduce having to type out the actual statuses to avoid misspelling.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
> +                  <Input placeholder="name" defaultValue={firstName} isRequired isDisabled />
Combine first and last name to display.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/DonationModal.jsx
>      submittedDate: PropTypes.string.isRequired,
Let's also mark these as not required because when the component is first created, data will most likely be null.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/DonationImagesContainer.jsx
> +  }),
The PropType for `data` should be 
```
data: PropTypes.arrayOf({
    id: PropTypes.string,
    imageURL: PropTypes.string,
    notes: PropTypes.string,
  }),
```

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/DonationFurnitureContainer.jsx
> +};
Edit `data` proptype to be an array of of a `Proptype.shape({...})`. Refer to the comment left on `DonationImagesContainer.`

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/DonationImagesContainer.jsx
> +        {displayedData.map(image => (
For some reason, I am getting an error trying to map this data so just in case let's check to make sure the array exists with [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). Add this for the furniture component as well.
```
displayed?.map( ...) 
```

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +      {/* <Button onClick={onEmailOpen}>Open Modal</Button> */}
Remove this. You can then remove the empty parent `<> </>` tags as well.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +
Since we're doing it this way, is there any reason to keep the `emailTemplate` separate from the modal content? If not, we can also combine these.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +  const [newMessage, setNewMessage] = useState();
Add an empty string to initialize.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +    if (status === 'cancel pickup') {
replace these strings with the `STATUS` config object.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +
On second look, the `emailTemp` looks to be the same as the `modalBody` so I don't think we need both. You can remove `emailTemp` and use the `modalBody` to create the `emailTemplate`.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +    makeModalBody: '',
Nit-pick: let's change these to the variable names without the "make" in front because it's not a function that's doing anything. Variables don't typically start with verbs.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +  }, [status]);
Let's extract this out into an object mapping the statues to an object with the `modalHeader` and `modalBody`. Then, the useEffect would simply be 
```
setModalContent(mappingObject[status]);
```

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +    makeModalBody: '',
Unless there is a reason there should be "make" in the front of the variables, the variable can be 
```
const [modalContent, setModalContent] = useState({
    header: '',
    body: '',
```

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/ImageModal.jsx
> +            <Textarea placeholder={notes} isDisabled />
Since we can't edit this text and disabling makes it hard to read, let's use a Chakra [Text](https://chakra-ui.com/docs/components/text) component.

2023-02-21 21:24 UTC, hang-m-cao commented on src/components/InventoryPage/EmailModal.jsx
> +              handleSubmit(e);
Status does not change on click.

2023-02-28 19:22 UTC, ctc-devops commented on src/components/InventoryPage/EmailModal.jsx
> +          console.log(routeInfo);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-03-01 02:01 UTC, hang-m-cao approved these changes
good job and thanks for all the hard work on this task! :)

2023-03-01 02:03 UTC, merged